### ISSUE TITLE
About the clean images for the soiling dataset

### ISSUE THREAD

**Issue by shtsang** [Leozyc-waseda/SoilingDataset#3]
As seen in the camera setup, one of the cameras is used for capturing the clean images, i.e. without any soils on lens.
But as in the soiling dataset that downloaded, it seems all are with soils.
Will there be any clean images provided?
Thanks.

**Comment by Leozyc-waseda** [comment]
I just uploaded the clean images, but the data was lost due to a lot of things. I can only find around 900 clean images.

https://drive.google.com/file/d/1SDPz4WkOex70rRfkQvPiRuDxUPHE65EU/view?usp=sharing
